### ISSUE TITLE
Implementing callback functions

### ISSUE THREAD

**Issue by biochem-fan** [antonbarty/cheetah-2017#19]
Thank you very much during SACLA workshop. I hope you enjoyed Kyoto.

As I told you during the workshop, I suggest implementation of callback functions
to realize facility and/or experiment specific extensions.
-   A function that is called just after cheetahProcessEventMultithreaded() by a worker thread.  
  This is used to apply pre-processings. For MPCCD, we need relative gain correction between panels.
-   A custom output function that is called instead of writeCXI or writeHDF5 when writeFlag is TRUE.  
  This is used to implement SACLA specific multievent HDF5 files. 
-   A pointer to user-defined type (that is, void *userdata) in cGlobal and cEventData.  
  The former is used to store run-specific metadata (sample ID, sample temperature, etc) and the latter is for frame-specific metadata (pulse diagnostics).
-   A function that is called at the end of worker() to destroy user-specific event data.

Currently I apply pre-precessings in the parent thread that calls cheetahProcessEventMultithreaded(), but I found this is rate-limiting when IO bottleneck is removed.

What do you think? If this is OK, I will re-implement my cheetah-sacla-api using callbacks and put it to my GitHub.

**Comment by antonbarty** [comment]
Dear Takanori

Valerio just pointed out to me the name you use on GitHub - and then I discovered this in my junk mail folder.
Many apologies for not replying sooner - the mail simply got lost in the wrong place.

Now I’ve been able to add you as a contributor to the main github repository.
A few of our team are going over to SACLA in the next week for some experiments.  Perhaps they will even try to use your fabulous Cheetah installation.

> Currently I apply pre-precessings in the parent thread that calls cheetahProcessEventMultithreaded(), but I found this is rate-limiting when IO bottleneck is removed.

Filipe and Carl found the same thing at SLAC - and as a result the LCLS code now has a data-copying thread (many can run in parallel) which in turn call the Cheetah processing thread.  That wasn’t possible until some changes were made to the LCLS API (event memory freed too soon)...

Valerio has had some success wrapping functions in Python for our online monitor, using MPI to distribute load across multiple nodes.  Looking to the future, I can see that eventually this approach could take over for near real time processing (we are currently limited to threads on one node). 

Best regards

Anton

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by biochem-fan** [comment]
Hi Anton,

Thank you very much for comments.

I created my 'folked' repository at https://github.com/biochem-fan/cheetah.
I will send you pull requests when a feature is ready for merging.

> Filipe and Carl found the same thing at SLAC - and as a result the LCLS code now has a 
> data-copying thread (many can run in parallel) which in turn call the Cheetah processing thread. 
> That wasn’t possible until some changes were made to the LCLS API (event memory freed too soon)...

Yes, I adapted same strategy for SACLA online API. With our API, we cannot create a thread for a frame, but have to create a thread for a detector panel. This makes synchronization much harder. We must make sure that all eight panels have been read, and then call  cheetahProcessEventMultithreaded(). As a consequence, my initial suggestion of callback functions turned out to be unsuitable, since a worker thread is created for each frame in Cheetah.

The new online API will be tested for the first time in our next beamtime (this weekend). If it works fine, I will upload my modifications to Cheetah.

**Comment by antonbarty** [comment]
Dear Takanore

> Yes, I adapted same strategy for SACLA online API. With our API, we cannot create a thread for a frame, but have to create a thread for a detector panel. This makes synchronization much harder. We must make sure that all eight panels have been read, and then call cheetahProcessEventMultithreaded(). As a consequence, my initial suggestion of callback functions turned out to be unsuitable, since a worker thread is created for each frame in Cheetah.
> 
> This is very interesting.  I dare not ask why each detector panel needs its own thread - there must be some logic behind that which I don’t understand. One has to live within the eco-system provided by the API and usually that involves some compromises and workarounds.  Getting data into the code can be bottleneck for sure, as can writing out the data, as you found (HDF5 demands a lock so one thread writes at a time). 

Andrew and Valerio have been working on an online monitor for Leo’s SACLA experiment next week. It will be interesting to see how the shared memory API works.   It would also be excellent to be able to install Cheetah and CrystFEL in one place for everyone rather than in someone’s home directory.  

A.

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by antonbarty** [comment]
Dear Anton,

  the online API will not be ready for next week, so for this
experiment, we will use Takanori's setup!

  Valerio
