### ISSUE TITLE
Cleaning up

### ISSUE THREAD

**Issue by FilipeMaia** [antonbarty/cheetah-2017#2]
I'm planning to some cleaning on the tree. Is there a reason why xtcProofReaderPkg,chuck_ana_pkg,arch,build,include and psana need to exist inside source/lcls-psana? cheetah_ana_pkg compiles fine without it. If no one objects I'll remove them.

**Comment by chuckie82** [comment]
They are used for checking xtcs and fluorescence.

**Comment by FilipeMaia** [comment]
You're talking about xtcProofReaderPkg and chuck_ana_pkg?

**Comment by chuckie82** [comment]
Yes.
I have no objections on removing build, include and psana.

**Comment by rkirian** [comment]
Hi Chuck, 

Is xtcProofReaderPkg and chuck_ana_pkg documented somewhere?  If not, I'd suggest that you make a development branch for yourself, and remove them from the master branch.  

(My build has crashed on these programs in the past - I had to remove the SConscript files).

Rick

**Comment by chuckie82** [comment]
They are the same packages as cheetah_ana_pkg, so these shouldn't cause
extra problems.
Filipe: Could you remove the two pkg's? I will add them in later.
Thanks.

**Comment by FilipeMaia** [comment]
Ok, then I'll remove xtcProofReaderPkg,chuck_ana_pkg,arch,build,include and psana from the master branch.

**Comment by antonbarty** [comment]
There is no reason for these to be where they are - other than that they are all psana modules.
It would probably be clearer if they were located elsewhere - this would separate problems with building things needed for Cheetah with problems related to things that may not be needed.

build, include are generated when compiling the modules;

It's a good idea to include psana so that we have a version that we know is compatible with the version of Cheetah in the repository.  It would be quite possible for someone to pull a wrong version then bug us with complaints about it not compiling.   Also, I have introduced some form of versioning - saving versions of the software with numbers, so that it's easier to roll back to an old version if needed for processing some old data.  Compilation of this will be easier if one doesn't also have to figure out how to dig up the appropriate psana version 

A.

**Comment by antonbarty** [comment]
> Is xtcProofReaderPkg and chuck_ana_pkg documented somewhere? If not, I'd suggest that you make a development branch for yourself, and remove them from the master branch. 

We wrote the XTC proof reader after having things such as laser on/off state not recorded in the XTC files.  Operator error in selecting which data was saved in the XTC.  It caused us no end of pain and nearly caused 2 shifts of data to be rendered worthless.  Hence the proof reader was born, to quickly check all required data was present.  

Compiling them can cause problems - how about document them and put them in another part of the tree.

**Comment by FilipeMaia** [comment]
I understand the idea of having our own psana but if we do relupgrade then
there's a good chance that we break something also (on the interface
between psana and the rest of the libraries, even if everything is fine
between psana and cheetah). I think a better idea is to refer to a
particular version of ana which we know is compatible with cheetah, for
example ana-0.7.18.

I'm going through the process of restructuring the directory structure with
the aim of making the code easy to compile (I'm doing it on the easybuild
branch).
I put libcheetah cheetah-myana and cheetah_ana_mod in 3 separate
directories so they can easily be built separately. I've also
got cheetah_ana_mod to compile without using scons (using cmake instead),
and with only requiring portable/sw/releases/ana-current

The idea it should compile out of the box in psexport, cfelsgi and here,
and everywhere else you just have to tell it where ana-current and hdf5 is.
The resulting binaries should also know where to find libraries so no
LD_LIBRARY_PATH messing around, but I still didn't get there.

**Comment by FilipeMaia** [comment]
The easybuild branch now builds without issue at Uppsala, SLAC and cfelsgi. 
It also builds psana in such a way that you can run it from the build directory without setting any LD_LIBRARY_PATHs and it will find the necessary libraries.
To build it just do:
mkdir build
cmake .. (or "ccmake .." if you want to interact)
make

Let me know how it goes.

**Comment by antonbarty** [comment]
Hi Filipe

I hope it works as easily as you make it sounds.
Don't forget to update some documentation somewhere with instructions - or someone will pester you down the line.

A.

**Comment by FilipeMaia** [comment]
I've deleted the "easy_build" branch. From now on please use the "developer" branch instead. Installation instructions under the "INSTALL" file.
