### ISSUE TITLE
MinPeakSeparation is broken

### ISSUE THREAD

**Issue by biochem-fan** [antonbarty/cheetah-2017#21]
It seems that MinPeakSeparation is broken. When it is not 0, all peaks are rejected (at least with peakfinder6).

In https://github.com/antonbarty/cheetah/blob/master/source/libcheetah/src/peakfinders.cpp#L157
killNearbyPeaks() should be called AFTER peak_com_{xyz}_assembled are set up in few lines later.

**Comment by antonbarty** [comment]
Yes, this never really got debugged properly
(hasn’t affected me as it’s an option I’ve not been using; we should fix it if others need it)

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by biochem-fan** [comment]
Thanks for confirmation. 
I will send pull request when our beamtime is over.

**Comment by antonbarty** [comment]
Ah - the fluffy of bug-fixing during beamtime, which is when If ind I do most of my changes too.

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by biochem-fan** [comment]
Could you please check and cherry-pick my commit to fix this?
https://github.com/biochem-fan/cheetah/commit/ae6a184e8f3d4953ffc01bedf233773da29b254b

(I can merge myself, but I don't want to mess things up. Double-checking by others is always good)

**Comment by antonbarty** [comment]
Thank-you very much - I’ve merged all of those in as they did make sense.

I must admit to not using peakfinder6 much myself, so it’s not a bit of the code that I ever get to debug much.  Thanks for spotting it.

Cheers

Anton

(At LCLS, with time on my hands to merge things into the system and test them)

A.

**Comment by biochem-fan** [comment]
Thank you very much for merging.

**Comment by antonbarty** [comment]
Thank-you for spotting (and fixing) the bugs.

I hope it works!

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/
