### ISSUE TITLE
Two bugs in peakhinder6

### ISSUE THREAD

**Issue by biochem-fan** [antonbarty/cheetah-2017#22]
In https://github.com/antonbarty/cheetah/blob/master/source/libcheetah/src/peakfinders.cpp#L1707
maxI should be initialized to zero for every new (potential) peak.

In https://github.com/antonbarty/cheetah/blob/master/source/libcheetah/src/peakfinders.cpp#L1789

```
peaklist->peakNpix += 1;
peaklist->peak_npix[counter] = 1;
```

nat should be added instead of 1.

There is also a bug that sometimes peak_com_{xy} go outside the image range. I haven't tracked it down yet. 

Yes, we use hithinder6. Which do you usually use?

**Comment by antonbarty** [comment]
Hi Takanori

> Yes, we use hithinder6. Which do you usually use?
> 
> Usually peakfinder8
> This one first calculates signal-to-noise and offset as a function of radius, then applies a radially-dependent threshold based where threshold(r) = offset + SNR \* sigma(r); threshold(r) = maximum[threshold(r), ADCthresh].

I found this enables weak peaks near the centre to be detected while not detection false peaks in the water ring (because sigma is higher in the water ring, so the threshold automatically becomes more stringent).    The ADCthreshold basically provides a floor value, so that blank frames with very low sigma don’t become full of false peaks.

**Comment by biochem-fan** [comment]
Thank you very much for your advice. 
I found that our images have asymmetric shadows (from injector, etc) and radial averaging is not very suitable. So I keep using hitfinder6.

Fix for this:
https://github.com/biochem-fan/cheetah/commit/1a35d16210cc86424d1c215a2448163c35e5306e
https://github.com/biochem-fan/cheetah/commit/ae6a184e8f3d4953ffc01bedf233773da29b254b

**Comment by antonbarty** [comment]
Hi 

> I found that our images have asymmetric shadows (from injector, etc) and radial averaging is not very suitable. So I keep using hitfinder6.
> 
> You are right - this does happen, and it does confuse the radial averaging. 

There is a fix, in the form of a  ‘peak mask’, which tells Cheetah peak finding and radial averaging not to look in a certain region.  
It’s ‘1’ where analysis should be performed, and ‘0’ for regions to be ignored.  We use this to mask out such shadows, and also streaks from the jet.

Hope this helps

A.
