### ISSUE TITLE
Cleaning up old merged branches

### ISSUE THREAD

**Issue by FilipeMaia** [antonbarty/cheetah-2017#4]
Does anyone object to deleting old merged branches?

**Comment by sellberg** [comment]
This would be great since it's a bit confusing to know what's active when there are so many unused branches

**Comment by antonbarty** [comment]
> Does anyone object to deleting old merged branches?

Cleaning up is good;
However, there are some branches that should be kept

To keep:  
For example, specific versions (v2013.2), and copies archived from something that worked at certain beamtimes (cxi52212).  These are dead-end branches with no further development, but make it easy for people to 'roll back' to something that worked or what was used for analysis in a given if needed. 

To clean up: Everything else
There are some branches - for example, and 'anton' branch, that come and go and come and go as I test and try things, then get rid of them once done with the playing around.  Those sort should be deleted.

Cheers

A.

**Comment by FilipeMaia** [comment]
Git can tag certain commits, which can be used exactly to specify that certain commits are more important than others. Instead of having these branches that are exactly like the master branch but stop at some point in the past we can use tags.
http://learn.github.com/p/tagging.html

What do you think?

**Comment by FilipeMaia** [comment]
I've deleted several branches and created tags instead.
